In [3]:
import pandas as pd
import requests

In [10]:
params = {
    "api_key": "8265bd1679663a7ea12ac168da84d2e8",
    "language": "en-US",
    "page": 471
}

In [11]:
response = requests.get(url,params=params)
print(response.status_code)
data=response.json()

200

In [12]:
df = pd.DataFrame(data['results'])

In [13]:
df

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/x2vgmjG6yPh6dT6U4057KqsWXKh.jpg,"[53, 27]",27414,"Silent Night, Deadly Night",en,"Silent Night, Deadly Night",After a man dressed as Santa Claus brutally mu...,3.4241,/ypj2JwAN4vWcc4zSqFCTgUwMbJV.jpg,1984-11-09,False,False,5.900,464
1,False,/raQIYTSZ7vtHgqzZBX4oDj9Tp1C.jpg,"[35, 14, 10749]",13477,When in Rome,en,When in Rome,"Disillusioned with romance, Beth, an ambitious...",4.1382,/pteIGpJpgh2aUh3jMqZnomB1rw1.jpg,2010-01-29,False,False,5.915,1310
2,False,/gvNkYKcP3olvxqOSkxLjXK9DLby.jpg,"[28, 10751, 14, 12]",11649,Masters of the Universe,en,Masters of the Universe,When He-Man is driven from Eternia after Skele...,6.7256,/gaUecXFd31V68yOTJPJYaB9YhAf.jpg,1987-08-07,False,False,5.915,1195
3,False,/bL41GVWvp4YJDJ50PDcxaN4cds9.jpg,"[12, 28, 14]",1995,Lara Croft: Tomb Raider,en,Lara Croft: Tomb Raider,"Orphaned heiress, English aristocrat and intre...",9.5254,/sJpl1EfHGZhbKtZ3fWTlwrpM1tH.jpg,2001-06-15,False,False,5.915,6737
4,False,/ryBUkjVLKjSJOTgBfxHrdu7rxG0.jpg,"[28, 12, 27, 878, 53]",1450,Blood: The Last Vampire,en,Blood: The Last Vampire,"On the surface, Saya is a stunning 16-year-old...",7.4582,/uzuYpbdFkNYqnBdOvhWqZxhHa5C.jpg,2009-04-02,False,False,5.915,443
5,False,/iwkWvcXcP8M4r9HLglhVEhgGyVu.jpg,"[28, 27]",1001311,Under Paris,fr,Sous la Seine,In order to save Paris from an international b...,6.8630,/qZPLK5ktRKa3CL4sKRZtj8UlPYc.jpg,2024-06-04,False,False,5.914,1472
6,False,/nJYAAOk74VjPlwz34jWFh8MPw2r.jpg,"[35, 878, 27]",664574,Silent Night,en,Silent Night,"Nell, Simon, and their boy Art are ready to we...",4.5537,/bfUO1SBTfgcK77em3lOuRFY2uLc.jpg,2021-12-03,False,False,5.900,630
7,False,/uVH4JeqPyVHWVwsYce1z8CxVG36.jpg,"[27, 53]",448194,Pyewacket,en,Pyewacket,"A frustrated, angry teenage girl awakens somet...",2.9875,/3ET9MWmIx2ny2KP5mqY9ceb0WxF.jpg,2017-12-08,False,False,5.914,365
8,False,/9Sd3RuIbnFCA4SX8CiBsp4x1XPd.jpg,"[18, 53]",418437,Unforgettable,en,Unforgettable,"Barely coping with the end of her marriage, Te...",3.3079,/jKyjJu3N0bcF9TzcyGLb0Nn6Uqq.jpg,2017-03-06,False,False,5.900,703
9,False,/dfU9xyEEyLxvZ5unTn05Whm9Lce.jpg,"[28, 14]",9312,Mortal Kombat,en,Mortal Kombat,For nine generations an evil sorcerer has been...,7.2219,/9YhpvhhvLrtL1wlwEfpVL16GI9d.jpg,1995-08-18,False,False,5.914,2699
10,False,/yRtZmZa2bmDYaOKygG7IaroSXwg.jpg,"[28, 80, 53]",249070,Hitman: Agent 47,en,Hitman: Agent 47,An assassin teams up with a woman to help her ...,7.5322,/cx9AOBOv9Qf5ufZYQMbfTV7w7VY.jpg,2015-08-20,False,False,5.900,3405
11,False,/g2EUWSPVSLyzIkrKdxuHSF2wGWh.jpg,"[28, 27, 53, 80]",1030987,Sympathy for the Devil,en,Sympathy for the Devil,After being forced to drive a mysterious passe...,3.5437,/afGdVMa80LMs6ibLP22CwM5uI4e.jpg,2023-07-20,False,False,5.900,357
12,False,/nxIqVM8Kqp6Ej21WiOncTwKzoG1.jpg,"[35, 878, 10749]",521007,Superintelligence,en,Superintelligence,When an all-powerful Superintelligence chooses...,6.1248,/podzoGfamoxObotrMMoH2WIc8nj.jpg,2020-11-26,False,False,5.900,404
13,False,/d7SWh0taIIfWyO2Yuy2wrO6z6p6.jpg,"[53, 12, 9648, 14]",208763,Forbidden Empire,ru,Вий,Early 18th century. Cartographer Jonathan Gree...,3.2198,/q0o9JQDp6PHY4zK0Aw1NHpyQyeo.jpg,2014-01-30,False,False,5.900,348
14,False,/srrzHjAzhYzUulBbllQCNekgnQb.jpg,"[28, 14, 27]",38321,Priest,en,Priest,"In an alternate world, humanity and vampires h...",7.4598,/fYHiA7LPGl9DG7m3DUs0Td1VMcO.jpg,2011-05-05,False,False,5.913,2667
15,False,/lLt7UMEHeMNnwLQJow8crCcmVU6.jpg,"[53, 9648, 878]",34069,Cargo,de,Cargo,The story of CARGO takes place on rusty space-...,2.1747,/5CFTLlGbRMtNI0ZyfRL4YC1qD4f.jpg,2009-09-24,False,False,5.900,464
16,False,/zKciMUA5pn4mDJTKiSkhjq3s3hm.jpg,"[12, 18, 27]",14138,Black Water,en,Black Water,"Based on true events, Grace, her boyfriend Ada...",2.2773,/7hd6iyViluCMOqIJz5TsiyBFqp9.jpg,2008-02-22,False,False,5.900,405
17,False,/mW4PtCR6h7XWEJVvSCZ8YWdJNCi.jpg,"[80, 27, 53]",8398,The Hitcher,en,The Hitcher,While driving through the New Mexico Desert du...,4.7780,/uc2lUHNB1bnoT5ejVCEYv6Vm9fS.jpg,2007-01-19,False,False,5.900,1044
18,False,/3ObFbh3rEQ2ZmOsJ6DvZazW72Oc.jpg,"[28, 35, 80]",616446,Brothers,en,Brothers,A reformed criminal's attempt at going straigh...,4.1151,/Akweo95FGyDpucYVT81h0SbX8Ky.jpg,2024-10-10,False,False,5.900,361
19,False,/acKU4LlCFgcbjsL2IjtD4mPzlq7.jpg,"[18, 12]",414001,The Mercy,en,The Mercy,"In 1968, Donald Crowhurst, an amateur sailor, ...",4.0119,/51qWwl16Mb0hqorgffCtyENwTPP.jpg,2018-02-09,False,False,5.900,313

In [14]:
df.shape

(20, 15)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              20 non-null     bool
 1   backdrop_path      20 non-null     str
 2   genre_ids          20 non-null     object
 3   id                 20 non-null     int64
 4   title              20 non-null     str
 5   original_language  20 non-null     str
 6   original_title     20 non-null     str
 7   overview           20 non-null     str
 8   popularity         20 non-null     float64
 9   poster_path        20 non-null     str
 10  release_date       20 non-null     str
 11  softcore           20 non-null     bool
 12  video              20 non-null     bool
 13  vote_average       20 non-null     float64
 14  vote_count         20 non-null     int64
dtypes: bool(3), float64(2), int64(2), object(1), str(7)
memory usage: 10.2+ KB

In [16]:
df.head()

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/x2vgmjG6yPh6dT6U4057KqsWXKh.jpg,"[53, 27]",27414,"Silent Night, Deadly Night",en,"Silent Night, Deadly Night",After a man dressed as Santa Claus brutally mu...,3.4241,/ypj2JwAN4vWcc4zSqFCTgUwMbJV.jpg,1984-11-09,False,False,5.900,464
1,False,/raQIYTSZ7vtHgqzZBX4oDj9Tp1C.jpg,"[35, 14, 10749]",13477,When in Rome,en,When in Rome,"Disillusioned with romance, Beth, an ambitious...",4.1382,/pteIGpJpgh2aUh3jMqZnomB1rw1.jpg,2010-01-29,False,False,5.915,1310
2,False,/gvNkYKcP3olvxqOSkxLjXK9DLby.jpg,"[28, 10751, 14, 12]",11649,Masters of the Universe,en,Masters of the Universe,When He-Man is driven from Eternia after Skele...,6.7256,/gaUecXFd31V68yOTJPJYaB9YhAf.jpg,1987-08-07,False,False,5.915,1195
3,False,/bL41GVWvp4YJDJ50PDcxaN4cds9.jpg,"[12, 28, 14]",1995,Lara Croft: Tomb Raider,en,Lara Croft: Tomb Raider,"Orphaned heiress, English aristocrat and intre...",9.5254,/sJpl1EfHGZhbKtZ3fWTlwrpM1tH.jpg,2001-06-15,False,False,5.915,6737
4,False,/ryBUkjVLKjSJOTgBfxHrdu7rxG0.jpg,"[28, 12, 27, 878, 53]",1450,Blood: The Last Vampire,en,Blood: The Last Vampire,"On the surface, Saya is a stunning 16-year-old...",7.4582,/uzuYpbdFkNYqnBdOvhWqZxhHa5C.jpg,2009-04-02,False,False,5.915,443

In [17]:
df=df[['title','overview','genre_ids']]

In [18]:
df

,title,overview,genre_ids
0,"Silent Night, Deadly Night",After a man dressed as Santa Claus brutally mu...,"[53, 27]"
1,When in Rome,"Disillusioned with romance, Beth, an ambitious...","[35, 14, 10749]"
2,Masters of the Universe,When He-Man is driven from Eternia after Skele...,"[28, 10751, 14, 12]"
3,Lara Croft: Tomb Raider,"Orphaned heiress, English aristocrat and intre...","[12, 28, 14]"
4,Blood: The Last Vampire,"On the surface, Saya is a stunning 16-year-old...","[28, 12, 27, 878, 53]"
5,Under Paris,In order to save Paris from an international b...,"[28, 27]"
6,Silent Night,"Nell, Simon, and their boy Art are ready to we...","[35, 878, 27]"
7,Pyewacket,"A frustrated, angry teenage girl awakens somet...","[27, 53]"
8,Unforgettable,"Barely coping with the end of her marriage, Te...","[18, 53]"
9,Mortal Kombat,For nine generations an evil sorcerer has been...,"[28, 14]"
10,Hitman: Agent 47,An assassin teams up with a woman to help her ...,"[28, 80, 53]"
11,Sympathy for the Devil,After being forced to drive a mysterious passe...,"[28, 27, 53, 80]"
12,Superintelligence,When an all-powerful Superintelligence chooses...,"[35, 878, 10749]"
13,Forbidden Empire,Early 18th century. Cartographer Jonathan Gree...,"[53, 12, 9648, 14]"
14,Priest,"In an alternate world, humanity and vampires h...","[28, 14, 27]"
15,Cargo,The story of CARGO takes place on rusty space-...,"[53, 9648, 878]"
16,Black Water,"Based on true events, Grace, her boyfriend Ada...","[12, 18, 27]"
17,The Hitcher,While driving through the New Mexico Desert du...,"[80, 27, 53]"
18,Brothers,A reformed criminal's attempt at going straigh...,"[28, 35, 80]"
19,The Mercy,"In 1968, Donald Crowhurst, an amateur sailor, ...","[18, 12]"

In [19]:
# Rename columns
df.rename(columns={
    "title": "name",
    "overview": "description",
    "genre_ids": "genre"
}, inplace=True)

print(df.head())

                         name  \
0  Silent Night, Deadly Night
1                When in Rome
2     Masters of the Universe
3     Lara Croft: Tomb Raider
4     Blood: The Last Vampire

                                         description                  genre
0  After a man dressed as Santa Claus brutally mu...               [53, 27]
1  Disillusioned with romance, Beth, an ambitious...        [35, 14, 10749]
2  When He-Man is driven from Eternia after Skele...    [28, 10751, 14, 12]
3  Orphaned heiress, English aristocrat and intre...           [12, 28, 14]
4  On the surface, Saya is a stunning 16-year-old...  [28, 12, 27, 878, 53]

In [20]:
df

,name,description,genre
0,"Silent Night, Deadly Night",After a man dressed as Santa Claus brutally mu...,"[53, 27]"
1,When in Rome,"Disillusioned with romance, Beth, an ambitious...","[35, 14, 10749]"
2,Masters of the Universe,When He-Man is driven from Eternia after Skele...,"[28, 10751, 14, 12]"
3,Lara Croft: Tomb Raider,"Orphaned heiress, English aristocrat and intre...","[12, 28, 14]"
4,Blood: The Last Vampire,"On the surface, Saya is a stunning 16-year-old...","[28, 12, 27, 878, 53]"
5,Under Paris,In order to save Paris from an international b...,"[28, 27]"
6,Silent Night,"Nell, Simon, and their boy Art are ready to we...","[35, 878, 27]"
7,Pyewacket,"A frustrated, angry teenage girl awakens somet...","[27, 53]"
8,Unforgettable,"Barely coping with the end of her marriage, Te...","[18, 53]"
9,Mortal Kombat,For nine generations an evil sorcerer has been...,"[28, 14]"
10,Hitman: Agent 47,An assassin teams up with a woman to help her ...,"[28, 80, 53]"
11,Sympathy for the Devil,After being forced to drive a mysterious passe...,"[28, 27, 53, 80]"
12,Superintelligence,When an all-powerful Superintelligence chooses...,"[35, 878, 10749]"
13,Forbidden Empire,Early 18th century. Cartographer Jonathan Gree...,"[53, 12, 9648, 14]"
14,Priest,"In an alternate world, humanity and vampires h...","[28, 14, 27]"
15,Cargo,The story of CARGO takes place on rusty space-...,"[53, 9648, 878]"
16,Black Water,"Based on true events, Grace, her boyfriend Ada...","[12, 18, 27]"
17,The Hitcher,While driving through the New Mexico Desert du...,"[80, 27, 53]"
18,Brothers,A reformed criminal's attempt at going straigh...,"[28, 35, 80]"
19,The Mercy,"In 1968, Donald Crowhurst, an amateur sailor, ...","[18, 12]"

In [21]:
genre_mapping = {
    28: "Action",
    12: "Adventure",
    16: "Animation",
    35: "Comedy",
    80: "Crime",
    99: "Documentary",
    18: "Drama",
    10751: "Family",
    14: "Fantasy",
    36: "History",
    27: "Horror",
    10402: "Music",
    9648: "Mystery",
    10749: "Romance",
    878: "Sci-Fi",
    10770: "TV Movie",
    53: "Thriller",
    10752: "War",
    37: "Western"
}

df["genre"] = df["genre"].apply(
    lambda ids: [genre_mapping[i] for i in ids if i in genre_mapping]
)

print(df[["name", "genre"]].head())

                         name                                          genre
0  Silent Night, Deadly Night                             [Thriller, Horror]
1                When in Rome                     [Comedy, Fantasy, Romance]
2     Masters of the Universe           [Action, Family, Fantasy, Adventure]
3     Lara Croft: Tomb Raider                   [Adventure, Action, Fantasy]
4     Blood: The Last Vampire  [Action, Adventure, Horror, Sci-Fi, Thriller]

In [22]:
df["genre"] = df["genre"].apply(
    lambda genres: genres[0] if genres else None
)

df.dropna(subset=["description", "genre"], inplace=True)

print(df.head())

                         name  \
0  Silent Night, Deadly Night
1                When in Rome
2     Masters of the Universe
3     Lara Croft: Tomb Raider
4     Blood: The Last Vampire

                                         description      genre
0  After a man dressed as Santa Claus brutally mu...   Thriller
1  Disillusioned with romance, Beth, an ambitious...     Comedy
2  When He-Man is driven from Eternia after Skele...     Action
3  Orphaned heiress, English aristocrat and intre...  Adventure
4  On the surface, Saya is a stunning 16-year-old...     Action

In [23]:
%pip install pandas numpy nltk beautifulsoup4 textblob scikit-learn

Requirement already satisfied: pandas in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.5.4)
Requirement already satisfied: nltk in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.10.4)
Requirement already satisfied: beautifulsoup4 in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (4.15.0)
Collecting textblob
  Downloading textblob-0.20.1-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: scikit-learn in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: defusedxml in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nltk) (2026.9.29)
Requirement already satisfied: tqdm in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from nltk) (4.70.1)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from beautifulsoup4) (3.0.4)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from joblib->nltk) (3.1.2)
Requirement already satisfied: six>=1.5 in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\Users\Dell\AppData\Local\Programs\Python\Python314\Lib\site-packages (from tqdm->nltk) (0.4.6)
Downloading textblob-0.20.1-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/625.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/625.0 kB ? eta -:--:--
   ---------------- ----------------------- 262.1/625.0 kB ? eta -:--:--
   ---------------------------------------- 625.0/625.0 kB 1.4 MB/s  0:00:00
Installing collected packages: textblob
Successfully installed textblob-0.20.1
Note: you may need to restart the kernel to use updated packages.

In [24]:
import nltk

nltk.download("stopwords")
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

# text preprocessing techniues

In [25]:
# lowercasing

df['lowercase']=df['description'].str.lower()
print(df[['description','lowercase']].head())

                                         description  \
0  After a man dressed as Santa Claus brutally mu...
1  Disillusioned with romance, Beth, an ambitious...
2  When He-Man is driven from Eternia after Skele...
3  Orphaned heiress, English aristocrat and intre...
4  On the surface, Saya is a stunning 16-year-old...

                                           lowercase
0  after a man dressed as santa claus brutally mu...
1  disillusioned with romance, beth, an ambitious...
2  when he-man is driven from eternia after skele...
3  orphaned heiress, english aristocrat and intre...
4  on the surface, saya is a stunning 16-year-old...

In [26]:
# removing html tags

import re
from bs4 import BeautifulSoup

def remove_html(text):
    return BeautifulSoup(str(text),'html.parser').get_text()

df['remove_html']=df['lowercase'].apply(remove_html)

In [27]:
df['remove_html']

0     after a man dressed as santa claus brutally mu...
1     disillusioned with romance, beth, an ambitious...
2     when he-man is driven from eternia after skele...
3     orphaned heiress, english aristocrat and intre...
4     on the surface, saya is a stunning 16-year-old...
5     in order to save paris from an international b...
6     nell, simon, and their boy art are ready to we...
7     a frustrated, angry teenage girl awakens somet...
8     barely coping with the end of her marriage, te...
9     for nine generations an evil sorcerer has been...
10    an assassin teams up with a woman to help her ...
11    after being forced to drive a mysterious passe...
12    when an all-powerful superintelligence chooses...
13    early 18th century. cartographer jonathan gree...
14    in an alternate world, humanity and vampires h...
15    the story of cargo takes place on rusty space-...
16    based on true events, grace, her boyfriend ada...
17    while driving through the new mexico desert du...
18    a reformed criminal's attempt at going straigh...
19    in 1968, donald crowhurst, an amateur sailor, ...
Name: remove_html, dtype: str

In [28]:
def remove_urls(text):
    return re.sub(r'https?//\S+|www\.S+','',text)
df['remove_url']=df['remove_html'].apply(remove_urls)

In [29]:
# remove punctuation

import string
def remove_punctuation(text):
    return text.translate(
        str.maketrans('','',string.punctuation)
    )
df['remove_punctuation']=df['remove_url'].apply(
    remove_punctuation
)

In [30]:
df['remove_punctuation']

0     after a man dressed as santa claus brutally mu...
1     disillusioned with romance beth an ambitious n...
2     when heman is driven from eternia after skelet...
3     orphaned heiress english aristocrat and intrep...
4     on the surface saya is a stunning 16yearold bu...
5     in order to save paris from an international b...
6     nell simon and their boy art are ready to welc...
7     a frustrated angry teenage girl awakens someth...
8     barely coping with the end of her marriage tes...
9     for nine generations an evil sorcerer has been...
10    an assassin teams up with a woman to help her ...
11    after being forced to drive a mysterious passe...
12    when an allpowerful superintelligence chooses ...
13    early 18th century cartographer jonathan green...
14    in an alternate world humanity and vampires ha...
15    the story of cargo takes place on rusty spacef...
16    based on true events grace her boyfriend adam ...
17    while driving through the new mexico desert du...
18    a reformed criminals attempt at going straight...
19    in 1968 donald crowhurst an amateur sailor end...
Name: remove_punctuation, dtype: str

In [31]:
# chat word tretment

chat_words = {
    "u": "you",
    "ur": "your",
    "r": "are",
    "btw": "by the way",
    "gr8": "great",
    "omg": "oh my god",
    "lol": "laughing out loud",
    "idk": "i do not know",
    "brb": "be right back"
}

def chat_conversion(text):
    words = text.split()

    new_words = [
        chat_words.get(word, word)
        for word in words
    ]

    return " ".join(new_words)

df["chat_treatment"] = df["remove_punctuation"].apply(
    chat_conversion
)

In [32]:
df["chat_treatment"]

0     after a man dressed as santa claus brutally mu...
1     disillusioned with romance beth an ambitious n...
2     when heman is driven from eternia after skelet...
3     orphaned heiress english aristocrat and intrep...
4     on the surface saya is a stunning 16yearold bu...
5     in order to save paris from an international b...
6     nell simon and their boy art are ready to welc...
7     a frustrated angry teenage girl awakens someth...
8     barely coping with the end of her marriage tes...
9     for nine generations an evil sorcerer has been...
10    an assassin teams up with a woman to help her ...
11    after being forced to drive a mysterious passe...
12    when an allpowerful superintelligence chooses ...
13    early 18th century cartographer jonathan green...
14    in an alternate world humanity and vampires ha...
15    the story of cargo takes place on rusty spacef...
16    based on true events grace her boyfriend adam ...
17    while driving through the new mexico desert du...
18    a reformed criminals attempt at going straight...
19    in 1968 donald crowhurst an amateur sailor end...
Name: chat_treatment, dtype: str

In [33]:
# spelling correction

from textblob import TextBlob

def spelling_correction(text):
    return str(TextBlob(text).correct())

df["spelling_correction"] = df["chat_treatment"].apply(
    spelling_correction
)

In [ ]:
# remove stopwords

from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

def remove_stopwords(text):
    words = text.split()

    return " ".join([
        word for word in words
        if word not in stop_words
    ])

df["remove_stopwords"] = df["spelling_correction"].apply(
    remove_stopwords
)

In [35]:
df["remove_stopwords"]

0     man dressed santa class brutally murders billy...
1     disillusioned romance beth ambitious new worke...
2     human driven eternal skeleton seizes castle gr...
3     orphan heiress english aristocrat intrepid arc...
4     surface say stunning 16yearold youthful exteri...
5     order save paris international bloodbath griev...
6     well simon boy art ready welcome friends famil...
7     frustrated angry teenage girl awaken something...
8     barely coming end marriage less connived learn...
9     nine generations evil sorcerer victorious hand...
10    assassin tears woman help find father uncover ...
11    forced drive mysterious passenger gunpoint man...
12    allpowerful superintelligence chooses study av...
13    early century cartographer jonathan green unde...
14    alternate world humanity campfires warned cent...
15    story cargo takes place rusty spacefreighter k...
16    based true events grace boyfriend adam younger...
17    driving new mexico desert rainy night college ...
18    reformed criminals attempt going straight deta...
19    1968 donald crowhurst amateur sailor endanger ...
Name: remove_stopwords, dtype: str

In [36]:
# handling emojis

def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002700-\U000027BF"
        "\U0001F900-\U0001F9FF"
        "]+",
        flags=re.UNICODE
    )

    return emoji_pattern.sub("", text)

df["remove_emojis"] = df["remove_stopwords"].apply(
    remove_emojis
)

In [37]:
# tokenization

from nltk.tokenize import word_tokenize

df['tokenization']=df['remove_emojis'].apply(
    word_tokenize
)

print(df['tokenization'].head())

0    [man, dressed, santa, class, brutally, murders...
1    [disillusioned, romance, beth, ambitious, new,...
2    [human, driven, eternal, skeleton, seizes, cas...
3    [orphan, heiress, english, aristocrat, intrepi...
4    [surface, say, stunning, 16yearold, youthful, ...
Name: tokenization, dtype: object

In [38]:
print(df['tokenization'].tail())

15    [story, cargo, takes, place, rusty, spacefreig...
16    [based, true, events, grace, boyfriend, adam, ...
17    [driving, new, mexico, desert, rainy, night, c...
18    [reformed, criminals, attempt, going, straight...
19    [1968, donald, crowhurst, amateur, sailor, end...
Name: tokenization, dtype: object

In [39]:
# stemming

from nltk.stem import PorterStemmer

ps=PorterStemmer()
def stemming(text):
    words=word_tokenize(text)

    return''.join([
        ps.stem(word)for word in words
    ])
df['stemming']=df['remove_emojis'].apply(stemming)

In [40]:
df['stemming']

0     mandresssantaclassbrutalmurderbillicharmantpar...
1     disillusromancbethambitinewworkertravelromesis...
2     humandriveneternskeletonseizcastlgrayskulstole...
3     orphanheiressenglisharistocratintrepidarchaeol...
4     surfacsaystun16yearoldyouthexteriorhidetorment...
5     ordersavepariinternbloodbathgrievscientistforc...
6     wellsimonboyartreadiwelcomfriendfamilipromispe...
7     frustratangriteenaggirlawakensomethwoodnaivper...
8     barecomeendmarriaglessconnivlearnhusbanddavidh...
9     ninegenerevilsorcervictorihandtohandbattlmorta...
10    assassintearwomanhelpfindfatheruncovmysterianc...
11    forcdrivemysteripassenggunpointmanfindhighstak...
12    allpowsuperintelligchoosstudiaveragpersonearth...
13    earlicenturicartographjonathangreenundertaksci...
14    alternworldhumancampfirwarncenturilastempirwar...
15    storicargotakeplacerustispacefreightkassandraw...
16    basetrueeventgraceboyfriendadamyoungersisterle...
17    drivenewmexicodesertraininightcollegstudentjim...
18    reformcriminattemptgostraightdetailreunitsanit...
19    1968donaldcrowhurstamateursailorendangfatefami...
Name: stemming, dtype: str

In [41]:
# lemmatization

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatization(text):
    words = word_tokenize(text)

    return " ".join([
        lemmatizer.lemmatize(word)
        for word in words
    ])

df["lemmatization"] = df["remove_emojis"].apply(
    lemmatization
)

In [ ]:
print(df.columns.tolist())

['name', 'description', 'genre', 'lowercase', 'remove_html', 'remove_url', 'remove_punctuation', 'chat_treatment', 'spelling_correction', 'remove_stopwords', 'remove_emojis', 'tokenization', 'stemming', 'lemmatization']

In [44]:
print(df[['name', 'genre', 'stemming', 'lemmatization']].head())

                         name      genre  \
0  Silent Night, Deadly Night   Thriller
1                When in Rome     Comedy
2     Masters of the Universe     Action
3     Lara Croft: Tomb Raider  Adventure
4     Blood: The Last Vampire     Action

                                            stemming  \
0  mandresssantaclassbrutalmurderbillicharmantpar...
1  disillusromancbethambitinewworkertravelromesis...
2  humandriveneternskeletonseizcastlgrayskulstole...
3  orphanheiressenglisharistocratintrepidarchaeol...
4  surfacsaystun16yearoldyouthexteriorhidetorment...

                                       lemmatization
0  man dressed santa class brutally murder billy ...
1  disillusioned romance beth ambitious new worke...
2  human driven eternal skeleton seizes castle gr...
3  orphan heiress english aristocrat intrepid arc...
4  surface say stunning 16yearold youthful exteri...

In [45]:
print(df.columns)

print(
    df[[
        "name",
        "description",
        "lowercase",
        "remove_html",
        "remove_url",
        "remove_punctuation",
        "chat_treatment",
        "spelling_correction",
        "remove_stopwords",
        "remove_emojis",
        "tokenization",
        "stemming",
        "lemmatization",
        "genre"
    ]].head()
)

Index(['name', 'description', 'genre', 'lowercase', 'remove_html',
       'remove_url', 'remove_punctuation', 'chat_treatment',
       'spelling_correction', 'remove_stopwords', 'remove_emojis',
       'tokenization', 'stemming', 'lemmatization'],
      dtype='str')
                         name  \
0  Silent Night, Deadly Night
1                When in Rome
2     Masters of the Universe
3     Lara Croft: Tomb Raider
4     Blood: The Last Vampire

                                         description  \
0  After a man dressed as Santa Claus brutally mu...
1  Disillusioned with romance, Beth, an ambitious...
2  When He-Man is driven from Eternia after Skele...
3  Orphaned heiress, English aristocrat and intre...
4  On the surface, Saya is a stunning 16-year-old...

                                           lowercase  \
0  after a man dressed as santa claus brutally mu...
1  disillusioned with romance, beth, an ambitious...
2  when he-man is driven from eternia after skele...
3  orphaned heiress, english aristocrat and intre...
4  on the surface, saya is a stunning 16-year-old...

                                         remove_html  \
0  after a man dressed as santa claus brutally mu...
1  disillusioned with romance, beth, an ambitious...
2  when he-man is driven from eternia after skele...
3  orphaned heiress, english aristocrat and intre...
4  on the surface, saya is a stunning 16-year-old...

                                          remove_url  \
0  after a man dressed as santa claus brutally mu...
1  disillusioned with romance, beth, an ambitious...
2  when he-man is driven from eternia after skele...
3  orphaned heiress, english aristocrat and intre...
4  on the surface, saya is a stunning 16-year-old...

                                  remove_punctuation  \
0  after a man dressed as santa claus brutally mu...
1  disillusioned with romance beth an ambitious n...
2  when heman is driven from eternia after skelet...
3  orphaned heiress english aristocrat and intrep...
4  on the surface saya is a stunning 16yearold bu...

                                      chat_treatment  \
0  after a man dressed as santa claus brutally mu...
1  disillusioned with romance beth an ambitious n...
2  when heman is driven from eternia after skelet...
3  orphaned heiress english aristocrat and intrep...
4  on the surface saya is a stunning 16yearold bu...

                                 spelling_correction  \
0  after a man dressed as santa class brutally mu...
1  disillusioned with romance beth an ambitious n...
2  when human is driven from eternal after skelet...
3  orphan heiress english aristocrat and intrepid...
4  on the surface say is a stunning 16yearold but...

                                    remove_stopwords  \
0  man dressed santa class brutally murders billy...
1  disillusioned romance beth ambitious new worke...
2  human driven eternal skeleton seizes castle gr...
3  orphan heiress english aristocrat intrepid arc...
4  surface say stunning 16yearold youthful exteri...

                                       remove_emojis  \
0  man dressed santa class brutally murders billy...
1  disillusioned romance beth ambitious new worke...
2  human driven eternal skeleton seizes castle gr...
3  orphan heiress english aristocrat intrepid arc...
4  surface say stunning 16yearold youthful exteri...

                                        tokenization  \
0  [man, dressed, santa, class, brutally, murders...
1  [disillusioned, romance, beth, ambitious, new,...
2  [human, driven, eternal, skeleton, seizes, cas...
3  [orphan, heiress, english, aristocrat, intrepi...
4  [surface, say, stunning, 16yearold, youthful, ...

                                            stemming  \
0  mandresssantaclassbrutalmurderbillicharmantpar...
1  disillusromancbethambitinewworkertravelromesis...
2  humandriveneternskeletonseizcastlgrayskulstole...
3  orphanheiressenglisharistocratintrepidarchaeol...
4  surfacsaystun16yearoldyouthexteriorhidetorment...

                                       lemmatization      genre
0  man dressed santa class brutally murder billy ...   Thriller
1  disillusioned romance beth ambitious new worke...     Comedy
2  human driven eternal skeleton seizes castle gr...     Action
3  orphan heiress english aristocrat intrepid arc...  Adventure
4  surface say stunning 16yearold youthful exteri...     Action

In [46]:
df.to_csv("movie_nlp_processed.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!